name: gvpr_emp_app

description: "GVPR Employee App"

publish_to: 'none'

version: 1.0.0+1

environment:
  sdk: ">=3.0.0 <4.0.0"

dependencies:
  flutter:
    sdk: flutter

  cupertino_icons: ^1.0.8
  http: ^1.2.1
  provider: ^6.1.2
  mobile_scanner: ^5.2.3
  shared_preferences: ^2.2.3
  url_launcher: ^6.3.0
  syncfusion_flutter_pdfviewer: ^27.2.5
  fl_chart: ^0.68.0
  google_fonts: ^6.2.1


dev_dependencies:
  flutter_test:
    sdk: flutter

  flutter_lints: ^6.0.0

flutter:
  uses-material-design: true