# Generated by Django 6.0.5 on 2026-05-16 10:18

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('employees', '0002_employee_appointment_letter_employee_joining_letter_and_more'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='employee',
            name='appointment_letter',
        ),
        migrations.RemoveField(
            model_name='employee',
            name='joining_letter',
        ),
        migrations.RemoveField(
            model_name='employeedocument',
            name='document_name',
        ),
    ]
