# Generated by Django 6.0.5 on 2026-05-17 06:13

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('employees', '0004_employee_photo'),
    ]

    operations = [
        migrations.AddField(
            model_name='employee',
            name='appointment_letter',
            field=models.FileField(blank=True, null=True, upload_to='documents/appointment_letters/'),
        ),
        migrations.AddField(
            model_name='employee',
            name='joining_letter',
            field=models.FileField(blank=True, null=True, upload_to='documents/joining_letters/'),
        ),
        migrations.AddField(
            model_name='employeedocument',
            name='document_name',
            field=models.CharField(default='Old Document', max_length=200),
            preserve_default=False,
        ),
    ]
