# Generated by Django 6.0.5 on 2026-05-19 03:07

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('employees', '0006_employee_created_at_employee_updated_at'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='employee',
            name='created_at',
        ),
        migrations.RemoveField(
            model_name='employee',
            name='updated_at',
        ),
    ]
