# Generated by Django 6.0.5 on 2026-05-30 18:58

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('employees', '0008_employee_aadhaar_employee_age_fitness_certificate_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='employee',
            name='eps_nps',
            field=models.CharField(blank=True, max_length=100, null=True),
        ),
        migrations.AddField(
            model_name='employee',
            name='family_details',
            field=models.TextField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='employee',
            name='pay',
            field=models.CharField(blank=True, max_length=100, null=True),
        ),
        migrations.AddField(
            model_name='employee',
            name='place_of_birth',
            field=models.CharField(blank=True, max_length=200, null=True),
        ),
        migrations.AddField(
            model_name='employee',
            name='posting_details',
            field=models.TextField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='employee',
            name='promotion',
            field=models.CharField(blank=True, max_length=200, null=True),
        ),
        migrations.AlterField(
            model_name='employee',
            name='category',
            field=models.CharField(blank=True, choices=[('Highly Skilled', 'Highly Skilled'), ('Skilled', 'Skilled'), ('Semi Skilled', 'Semi Skilled'), ('Un Skilled', 'Un Skilled')], max_length=20, null=True),
        ),
    ]
