# Generated by Django 6.0.5 on 2026-05-31 20:48

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('employees', '0009_employee_eps_nps_employee_family_details_and_more'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='employee',
            name='age_fitness_certificate',
        ),
        migrations.RemoveField(
            model_name='employee',
            name='emergency_contact_address',
        ),
        migrations.RemoveField(
            model_name='employee',
            name='emergency_contact_name',
        ),
        migrations.RemoveField(
            model_name='employee',
            name='emergency_mobile',
        ),
        migrations.RemoveField(
            model_name='employee',
            name='employee_register_no',
        ),
        migrations.RemoveField(
            model_name='employee',
            name='first_appointment_date',
        ),
        migrations.RemoveField(
            model_name='employee',
            name='lwf',
        ),
        migrations.RemoveField(
            model_name='employee',
            name='nominee_address',
        ),
        migrations.RemoveField(
            model_name='employee',
            name='owner_name',
        ),
        migrations.RemoveField(
            model_name='employee',
            name='place_of_employment',
        ),
        migrations.RemoveField(
            model_name='employee',
            name='token_number',
        ),
        migrations.RemoveField(
            model_name='employee',
            name='vocational_training_date',
        ),
        migrations.RemoveField(
            model_name='employee',
            name='vocational_training_number',
        ),
    ]
