# Generated by Django 6.0.5 on 2026-06-01 17:55

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('employees', '0010_remove_employee_age_fitness_certificate_and_more'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='employee',
            options={'permissions': (('view_dashboard', 'Can view dashboard'), ('import_employee_excel', 'Can upload employee Excel'), ('export_employee_excel', 'Can export employee Excel'), ('scan_employee_qr', 'Can use employee QR scanner'))},
        ),
    ]
